export { default as HomePage } from "./HomePage";
export { default as ProductsPage } from "./ProductsPage";
export { default as ProductPage } from "./ProductPage";
export { default as FavoritePage } from "./FavoritePage";
export { default as CartPage } from "./CartPage";
export { default as LoginPage } from "./LoginPage";
export { default as ProfilePage } from "./ProfilePage";
export { default as OrdersPage } from "./OrdersPage";
export { default as NotFoundPage } from "./NotFoundPage";
