import { IProduct } from "./types.js";

export const initialProducts: IProduct[] = [
  {
    id: 1,
    title: "Беспроводные наушники SoundPremium",
    price: 5990,
    description:
      "Наушники с активным шумоподавлением и автономностью до 30 часов.",
    category: "electronics",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 12,
    discount: 15,
  },
  {
    id: 2,
    title: "Спортивные смарт-часы ActiveFit",
    price: 3490,
    description:
      "Влагозащищенные часы с датчиком пульса и встроенным GPS-трекером.",
    category: "electronics",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 8,
    discount: 33,
  },
  {
    id: 3,
    title: "Худи Оверсайз Minimalist",
    price: 4200,
    description:
      "Удобное хлопковое худи свободного кроя для повседневной носки.",
    category: "clothing",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 25,
    discount: 10,
  },
  {
    id: 4,
    title: "Механическая клавиатура ClickyPro",
    price: 7500,
    description:
      "Компактная клавиатура с RGB подсветкой и возможностью горячей замены переключателей.",
    category: "electronics",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 4,
    discount: 50,
  },
  {
    id: 5,
    title: "Городской рюкзак UrbanShield",
    price: 2990,
    description:
      "Водонепроницаемый рюкзак с отделением для ноутбука до 15.6 дюймов.",
    category: "accessories",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 15,
    discount: 0,
  },
  {
    id: 6,
    title: "Кроссовки StreetWalker",
    price: 6800,
    description:
      "Легкие дышащие кроссовки с амортизирующей подошвой для бега и ходьбы.",
    category: "shoes",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 10,
    discount: 20,
  },
  {
    id: 7,
    title: "Пауэрбанк EnergyCell 20000mAh",
    price: 1990,
    description:
      "Портативный аккумулятор с поддержкой быстрой зарядки Power Delivery.",
    category: "electronics",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 40,
    discount: 5,
  },
  {
    id: 8,
    title: "Кожаный кошелек Classic Wallet",
    price: 2450,
    description:
      "Компактное портмоне из натуральной кожи с защитой от RFID-сканирования.",
    category: "accessories",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 18,
    discount: 0,
  },
  {
    id: 9,
    title: "Джинсовая куртка DenimVibe",
    price: 5300,
    description:
      "Классическая джинсовка из плотного хлопка с винтажным эффектом.",
    category: "clothing",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 7,
    discount: 0,
  },
  {
    id: 10,
    title: "Настольная лампа GlowControl",
    price: 1800,
    description:
      "Светодиодная лампа с регулировкой яркости и цветовой температуры.",
    category: "home",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 14,
    discount: 0,
  },
  {
    id: 11,
    title: "Игровая мышь PrecisionX",
    price: 4100,
    description:
      "Эргономичная мышь с оптическим сенсором высокого разрешения и программируемыми кнопками.",
    category: "electronics",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 22,
    discount: 25,
  },
  {
    id: 12,
    title: "Футболка Basic CottonБелая",
    price: 1200,
    description:
      "Базовая однотонная футболка из 100% органического премиум хлопка.",
    category: "clothing",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 50,
    discount: 0,
  },
  {
    id: 13,
    title: "Солнцезащитные очки RayBlock",
    price: 3100,
    description:
      "Стильные очки с поляризационными линзами и полной защитой от UV-лучей.",
    category: "accessories",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 9,
    discount: 0,
  },
  {
    id: 14,
    title: "Зимняя шапка CozyWarm",
    price: 1500,
    description:
      "Мягкая вязаная шапка с флисовой подкладкой для холодной погоды.",
    category: "clothing",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 30,
    discount: 0,
  },
  {
    id: 15,
    title: "Бутылка для воды HydroFlow",
    price: 990,
    description:
      "Спортивная матовая бутылка из экологичного пластика Tritan с маркером времени.",
    category: "accessories",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 35,
    discount: 0,
  },
  {
    id: 16,
    title: "Фитнес-браслет SlimBand",
    price: 2200,
    description:
      "Миниатюрный трекер активности с AMOLED экраном и мониторингом сна.",
    category: "electronics",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 17,
    discount: 0,
  },
  {
    id: 17,
    title: "Брюки Карго CargoNomad",
    price: 3900,
    description:
      "Прочные брюки с вместительными накладными карманами в стиле милитари.",
    category: "clothing",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 11,
    discount: 0,
  },
  {
    id: 18,
    title: "Коврик для мыши DeskPad XL",
    price: 1400,
    description:
      "Большой игровой коврик на весь стол с гладким покрытием Speed и прошитыми краями.",
    category: "accessories",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 20,
    discount: 0,
  },
  {
    id: 19,
    title: "Беспроводная колонка SoundBoom",
    price: 4800,
    description:
      "Портативная акустика с мощным басом и защитой от влаги по стандарту IPX7.",
    category: "electronics",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 6,
    discount: 0,
  },
  {
    id: 20,
    title: "Кожаный ремень PrimeStrap",
    price: 1750,
    description:
      "Классический ремень из цельной кожи с надежной металлической пряжкой.",
    category: "accessories",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 13,
    discount: 0,
  },
  {
    id: 21,
    title: "Спортивная сумка GymPack",
    price: 2600,
    description:
      "Вместительная сумка с изолированным вентилируемым отделением для обуви.",
    category: "accessories",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 16,
    discount: 0,
  },
  {
    id: 22,
    title: "Увлажнитель воздуха AirFresh",
    price: 3200,
    description:
      "Ультразвуковой увлажнитель с функцией ароматизации и мягкой ночной подсветкой.",
    category: "home",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 5,
    discount: 0,
  },
  {
    id: 23,
    title: "Домашние тапочки CloudSoft",
    price: 1100,
    description:
      "Теплые и невероятно мягкие тапочки со стелькой из пены с эффектом памяти.",
    category: "shoes",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 45,
    discount: 0,
  },
  {
    id: 24,
    title: "Кепка-бейсболка SnapbackClassic",
    price: 1350,
    description:
      "Универсальная шестипанельная кепка с регулируемой застежкой сзади.",
    category: "clothing",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 28,
    discount: 0,
  },
  {
    id: 25,
    title: "Зарядная станция 3-в-1 DockStation",
    price: 2990,
    description:
      "Беспроводная док-станция для одновременной зарядки смартфона, часов и наушников.",
    category: "electronics",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 10,
    discount: 0,
  },
  {
    id: 26,
    title: "Вязаный свитер CozyKnit",
    price: 4600,
    description: "Теплый фактурный свитер из мягкой полушерстяной пряжи.",
    category: "clothing",
    imageUrl: "http://localhost:5000/uploads/products/headphones.png",
    countInStock: 8,
    discount: 0,
  },
];
